import { PDF_EFieldType, PDF_IFieldVO } from '../../plugins-draggable-formula.api';

export const timeList: PDF_IFieldVO[] = [
  {
    id: '1',
    name: '截至上月(所在托管期)',
    indexType: PDF_EFieldType.时间,
    serialNumber: '1',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    id: '2',
    name: '累计(所在托管期)',
    indexType: PDF_EFieldType.时间,
    serialNumber: '1',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
];

export const numberList: PDF_IFieldVO[] = [
  {
    id: '1',
    name: '%',
    indexType: PDF_EFieldType.数字,
    serialNumber: '1',
    unit: '%',
    configureDataFlag: false,
    editable: true,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    id: '2',
    name: '123',
    indexType: PDF_EFieldType.数字,
    serialNumber: '2',
    unit: '',
    configureDataFlag: false,
    editable: true,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
];

export const operatorList: PDF_IFieldVO[] = [
  {
    name: '+',
    id: '1',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '1',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: '-',
    id: '2',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '2',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: 'x',
    id: '3',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '3',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: '/',
    id: '4',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '4',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: '=',
    id: '5',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '5',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: '(',
    id: '6',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '6',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: ')',
    id: '7',
    indexType: PDF_EFieldType.运算符,
    serialNumber: '7',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
];

export const deciderList: PDF_IFieldVO[] = [
  {
    name: '>',
    id: '1',
    indexType: PDF_EFieldType.判断符,
    serialNumber: '1',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    id: '2',
    indexType: PDF_EFieldType.判断符,
    serialNumber: '2',
    name: '≥',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    id: '3',
    indexType: PDF_EFieldType.判断符,
    serialNumber: '3',
    name: '<',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    id: '4',
    indexType: PDF_EFieldType.判断符,
    serialNumber: '4',
    name: '≤',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
  {
    name: '=',
    id: '5',
    indexType: PDF_EFieldType.判断符,
    serialNumber: '5',
    unit: '',
    configureDataFlag: false,
    editable: false,
    prefabricateFlag: false,
    configureFormulaFlag: false,
    value: '',
  },
];
