export enum DistributeQueryFunctionStrategyEnum {
	// 
	EXACT_LOC = 'EXACT_LOC',
	// 
	RELATIVE_LOC_LEVEL_ABSOLUTE_FUNCTION_LEVEL = 'RELATIVE_LOC_LEVEL_ABSOLUTE_FUNCTION_LEVEL',
	// 
	RELATIVE_LOC_LEVEL_RELATIVE_FUNCTION_LEVEL = 'RELATIVE_LOC_LEVEL_RELATIVE_FUNCTION_LEVEL'
}