/** 树绑点模块 */
declare namespace TreeBindingModule {
  /**
   * 节点信息
   */
  interface TreeBindingInfo {
    formulaInfoList: FormulaInfo[];
    treeId: number;
    treeName: string;
  }
  /**
   * 绑点列表
   */
  interface FormulaInfo {
    autoGenerated: number;
    energyCode: string;
    formula: string;
    id: number;
    name: string;
    pointInfoList: PointInfo[];
  }
  /**
   * 绑点信息
   */
  interface PointInfo {
    concentratorId: number;
    concentratorName: string;
    deviceId: number;
    deviceName: string;
    pointName: string;
    pointNumber: number;
    standardPointCode: string;
    pointId?: number;
  }
  /**
   * 站点 设备
   */
  interface ConcentratorInfo {
    id: number;
    name: string;
    devicePointInfoList?: DevicePointInfoListInfo[];
  }
  /**
   * 点位
   */
  interface DevicePointInfoListInfo {
    id: number;
    deviceId: number;
    name: string;
    pointNumber: number;
    standardPointCode: string;
  }
}
